import type { ConfirmedSkillOverride } from "./confirmed-skill-overrides.ts";

export const structuredServantBatchOverrides: Record<string, ConfirmedSkillOverride> = {
  "servant.boudica.skill.sc-boudica-1": {
    activation: "phase", windows: ["combat"], steps: ["player-window"],
    passiveEventTypes: ["combat.resolved"],
    requiresActiveCard: true,
    requiresTrueName: true,
    revealsTrueNameOnPlay: true,
    limit: "once-per-game",
    protectsControllerCardsFromOpponents: true,
    abilities: [
      {
        id: "residual-guard",
        name: "残留保护",
        activation: "passive",
        windows: [],
        requiresActiveCard: true,
      },
      {
        id: "wheel-forward",
        name: "守护车轮移动",
        activation: "phase",
        windows: ["combat"],
        steps: ["player-window"],
        abilityCost: 2,
        requiresActiveCard: true,
      },
      {
        id: "wheel-power",
        name: "守护车轮",
        activation: "phase",
        windows: ["combat"],
        steps: ["player-window"],
        requiresActiveCard: true,
      },
    ],
    handlerId: "core.structured-skill", supportLevel: "FULL",
    rules: {
      schemaVersion: "fd-card-authoring-v1",
      abilities: [
        {
          id: "residual-guard", kind: "passive",
          printedClause: "残留：对手不能关闭你的牌。",
          execution: { mode: "automatic" },
          conditions: [{ type: "source_active" }],
          effects: [{
            type: "info_note",
            note: "由 protectsControllerCardsFromOpponents 执行：此牌激活时，对手不能关闭控制者拥有的牌。",
          }],
        },
        {
          id: "wheel-forward", kind: "phase_action", activation: { phase: "combat" },
          printedClause: "战斗阶段：花费2点魔力，沿着箭头移动一步。",
          execution: { mode: "automatic" },
          conditions: [{ type: "source_active" }],
          effects: [{ type: "move_forward", steps: 1 }],
        },
        {
          id: "wheel-power", kind: "phase_action", activation: { phase: "combat" },
          printedClause: "战斗阶段：获得5点合计威力，战斗阶段结束后关闭此牌。",
          execution: { mode: "automatic" },
          conditions: [{ type: "source_active" }],
          effects: [{ type: "combat_power_bonus", amount: 5 }],
        },
        {
          id: "combat-end-close", kind: "passive", activation: { phase: "combat" },
          printedClause: "战斗阶段结束后关闭此牌。",
          execution: { mode: "automatic" },
          conditions: [
            { type: "event_type_is", eventType: "combat.resolved" },
            { type: "source_active" },
          ],
          effects: [{ type: "close_owned_active_cards_by_definition", definitionId: "self", count: 1 }],
        },
      ],
    },
  },
  "servant.chiron.skill.sc-chiron-2": {
    activation: "passive",
    windows: [],
    handlerId: "core.structured-skill",
    passiveEventTypes: ["combat.resolved"],
    supportLevel: "FULL",
    rules: {
      schemaVersion: "fd-card-authoring-v1",
      abilities: [{
        id: "wisdom-of-divine-gift",
        kind: "passive",
        activation: { eventType: "combat.resolved" },
        printedClause: "被动/战斗阶段：战斗结束后，你可选择你的基础牌和一张与你战斗的对手的相同属性的基础牌；选择的2张牌互相加入对方的手牌中，若你的牌拥有更高的基本威力，获得2点战果。",
        execution: { mode: "automatic" },
        conditions: [
          { type: "at_battlefield" },
        ],
        effects: [{
          type: "choose_cards",
          target: "controller",
          zone: "attack",
          basicOnly: true,
          activeOnly: true,
          minCount: 0,
          maxCount: 1,
          payloadKey: "chironOwnCardId",
          then: [{
            type: "choose_cards",
            target: { scope: "same_battlefield_opponents" },
            zone: "attack",
            basicOnly: true,
            activeOnly: true,
            sameAttributeAsPayloadKey: "chironOwnCardId",
            minCount: 0,
            maxCount: 1,
            payloadKey: "chironOpponentCardId",
            then: [
              {
                type: "transfer_selected_cards",
                payloadKey: "chironOwnCardId",
                target: { scope: "selected_card_owners", payloadKey: "chironOpponentCardId" },
                destination: "hand",
              },
              {
                type: "transfer_selected_cards",
                payloadKey: "chironOpponentCardId",
                target: "controller",
                destination: "hand",
              },
              {
                type: "gain_victory_points_if_selected_card_base_power_greater",
                leftPayloadKey: "chironOwnCardId",
                rightPayloadKey: "chironOpponentCardId",
                amount: 2,
              },
            ],
          }],
        }],
      }],
    },
  },
  "servant.arthur.skill.sc-arthur-1": {
    activation: "phase",
    windows: ["action"],
    steps: ["player-window"],
    requiresActiveCard: true,
    handlerId: "core.structured-skill",
    supportLevel: "FULL",
    rules: {
      schemaVersion: "fd-card-authoring-v1",
      abilities: [{
        id: "contract-victory-sword",
        kind: "phase_action",
        activation: { phase: "action" },
        requiresActiveCard: true,
        printedClause: "【真名解放】\n行动阶段：将任意数量亚瑟的技能移出游戏。每张移除的技能为[契约胜利之剑]增加5点威力以及2点消耗持续到游戏结束。",
        execution: { mode: "automatic" },
        effects: [{
          type: "choose_cards",
          target: "controller",
          zone: "servant-skills",
          definitionIds: [
            "servant.arthur.skill.sc-arthur-2",
            "servant.arthur.skill.sc-arthur-3",
          ],
          minCount: 0,
          maxCount: 99,
          payloadKey: "arthurRemovedSkillIds",
          then: [
            {
              type: "remove_selected_cards",
              zone: "servant-skills",
              payloadKey: "arthurRemovedSkillIds",
              minCount: 1,
              maxCount: 99,
            },
            {
              type: "source_card_power_bonus",
              id: "contract-victory-sword-power",
              amount: { type: "payload_count", key: "arthurRemovedSkillIds", multiply: 5 },
              duration: "game",
            },
            {
              type: "add_card_cost_modifier",
              id: "contract-victory-sword-cost",
              definitionId: "servant.arthur.skill.sc-arthur-1",
              amount: { type: "payload_count", key: "arthurRemovedSkillIds", multiply: 2 },
              duration: "game",
            },
          ],
        }],
      }],
    },
  },
  "servant.donquixote.skill.sc-donquixote-1": {
    activation: "phase",
    windows: ["action"],
    steps: ["player-window"],
    requiresActiveCard: true,
    handlerId: "core.structured-skill",
    passiveEventTypes: ["combat.resolved"],
    supportLevel: "FULL",
    rules: {
      schemaVersion: "fd-card-authoring-v1",
      abilities: [
        {
          id: "foolish-courage",
          kind: "passive",
          activation: { eventType: "combat.resolved" },
          requiresActiveCard: true,
          printedClause: "愚者之勇-若你战败，此牌魔力消耗与威力+3直至游戏结束（至多+12）。",
          execution: { mode: "automatic" },
          conditions: [
            { type: "source_active" },
            { type: "event_player_lost_combat" },
          ],
          effects: [
            {
              type: "source_card_power_bonus",
              id: "foolish-courage-power",
              amount: 3,
              maxTotal: 12,
              duration: "game",
            },
            {
              type: "add_card_cost_modifier",
              id: "foolish-courage-cost",
              definitionId: "servant.donquixote.skill.sc-donquixote-1",
              amount: 3,
              maxTotal: 12,
              duration: "game",
            },
          ],
        },
        {
          id: "windmill-charge",
          kind: "phase_action",
          activation: { phase: "action" },
          requiresActiveCard: true,
          printedClause: "向风车的冲锋-行动阶段：若你独自位于一处战场，获得该战场的竞争战果。",
          execution: { mode: "automatic" },
          conditions: [
            { type: "at_battlefield" },
            { type: "target_count_equals", scope: "same_battlefield_players", count: 1 },
          ],
          effects: [{ type: "gain_current_battlefield_competition_reward" }],
        },
      ],
    },
  },
  "servant.semiramis.skill.sc-semiramis-3": {
    activation: "phase",
    windows: ["combat"],
    steps: ["player-window"],
    requiresActiveCard: true,
    handlerId: "core.structured-skill",
    supportLevel: "FULL",
    rules: {
      schemaVersion: "fd-card-authoring-v1",
      abilities: [{
        id: "poison-dragon",
        kind: "phase_action",
        activation: { phase: "combat" },
        requiresActiveCard: true,
        printedClause: "【真名解放】\n只有在【阵地作成】激活时才可使用此牌。\n毒龙-战斗阶段：使所有与你处于同一战场，且前哨阶段部署于此的对手【败北】。",
        execution: { mode: "automatic" },
        conditions: [
          { type: "at_battlefield" },
          { type: "source_active" },
          { type: "owned_active_card_by_definition", definitionId: "servant.semiramis.skill.sc-semiramis-2" },
          {
            type: "target_count_at_least",
            count: 1,
            target: {
              scope: "same_battlefield_opponents",
              where: [{ type: "player_flag_equals_controller_location", key: "deploymentLocationId" }],
            },
          },
        ],
        effects: [{
          type: "defeat_player",
          target: {
            scope: "same_battlefield_opponents",
            where: [{ type: "player_flag_equals_controller_location", key: "deploymentLocationId" }],
          },
        }],
      }],
    },
  },
  "servant.medea.skill.sc-medea-1": {
    activation: "passive",
    windows: [],
    requiresActiveCard: true,
    handlerId: "core.structured-skill",
    passiveEventTypes: ["combat.resolved"],
    supportLevel: "FULL",
    rules: {
      schemaVersion: "fd-card-authoring-v1",
      abilities: [{
        id: "divine-words-recover-rule-breaker",
        kind: "passive",
        activation: { eventType: "combat.resolved" },
        requiresActiveCard: true,
        printedClause: "【真名解放】\n战斗阶段：若你在战斗中失败，将一张被移除的【万符必应破戒】加入你的技能区。",
        execution: { mode: "automatic" },
        conditions: [
          { type: "source_active" },
          { type: "event_player_lost_combat" },
        ],
        effects: [{
          type: "return_card_by_definition",
          definitionId: "servant.medea.skill.sc-medea-np",
          fromZone: "removed",
          destination: "servant-skills",
          face: "up",
        }],
      }],
    },
  },
  "servant.medea.skill.sc-medea-np": {
    activation: "phase",
    windows: ["action"],
    steps: ["player-window"],
    requiresActiveCard: true,
    limit: "once-per-game",
    handlerId: "core.structured-skill",
    supportLevel: "FULL",
    rules: {
      schemaVersion: "fd-card-authoring-v1",
      abilities: [{
        id: "rule-breaker",
        kind: "phase_action",
        activation: { phase: "action" },
        requiresActiveCard: true,
        printedClause: "【真名解放】<每局游戏限一次>\n行动阶段：你所在战场的一名玩家失去一枚令咒，若其原本只有一枚或更少的令咒，另其【败北】。若其原本没有令咒，你总威力+10。",
        execution: { mode: "automatic" },
        conditions: [{ type: "at_battlefield" }],
        targets: [{ id: "targetPlayerId", type: "player", scope: "same_battlefield_players" }],
        effects: [{
          type: "lose_command_seals",
          target: { scope: "selected_same_battlefield_player" },
          amount: 1,
          then: [
            {
              type: "if_condition",
              conditions: [{ type: "target_command_seals_at_most", target: { scope: "selected_same_battlefield_player" }, value: 1 }],
              then: [{ type: "defeat_player", target: { scope: "selected_same_battlefield_player" } }],
            },
            {
              type: "if_condition",
              conditions: [{ type: "target_command_seals_equals", target: { scope: "selected_same_battlefield_player" }, value: 0 }],
              then: [{ type: "combat_power_bonus", amount: 10 }],
            },
          ],
        }],
      }],
    },
  },
  "servant.frank.skill.sc-frank-1": {
    activation: "phase",
    windows: ["combat"],
    steps: ["player-window"],
    requiresEightMana: false,
    requiresActiveCard: true,
    handlerId: "core.structured-skill",
    supportLevel: "FULL",
    rules: {
      schemaVersion: "fd-card-authoring-v1",
      abilities: [{
        id: "galvanism",
        kind: "phase_action",
        activation: { phase: "combat" },
        requiresActiveCard: true,
        printedClause: "你拥有的魔力少于8点也可使用此牌。战斗阶段：关闭任意一张与你同一地点的魔术属性基础牌。若你成功使其无效，获得等同于该牌基本威力的魔力。",
        execution: { mode: "automatic" },
        effects: [
          {
            type: "close_selected_card",
            target: { scope: "selected_same_location_player" },
            payloadKey: "targetInstanceId",
            zone: "attack",
            ownerScope: "same_location_players",
            basicOnly: true,
            attributes: ["魔术"],
          },
          { type: "gain_mana_from_selected_card_base_power", payloadKey: "targetInstanceId" },
        ],
      }],
    },
  },
  "servant.kintoki.skill.sc-kintoki-3": {
    activation: "phase",
    windows: ["combat"],
    steps: ["player-window"],
    requiresActiveCard: true,
    handlerId: "core.structured-skill",
    supportLevel: "FULL",
    rules: {
      schemaVersion: "fd-card-authoring-v1",
      abilities: [{
        id: "golden-eater",
        kind: "phase_action",
        activation: { phase: "combat" },
        requiresActiveCard: true,
        printedClause: "【真名解放】战斗阶段：将一张被移除游戏的【黄金冲击】加入你的技能区，你可以花费7点魔力将另一张黄金冲击也加入你的技能区。若你位于一处战场，每加入一张【黄金冲击】便获得2点战果。",
        execution: { mode: "automatic" },
        conditions: [{ type: "at_battlefield" }],
        effects: [{
          type: "choose_one",
          options: [
            {
              id: "one",
              effects: [{
                type: "return_cards_by_definitions",
                definitionIds: ["servant.kintoki.skill.sc-kintoki-1", "servant.kintoki.skill.sc-kintoki-2"],
                fromZone: "removed",
                destination: "servant-skills",
                face: "up",
                count: 1,
                payloadKey: "goldenShockReturned",
                then: [{ type: "gain_victory_points", amount: { type: "payload_number", key: "goldenShockReturned", multiply: 2 } }],
              }],
            },
            {
              id: "two",
              effects: [
                { type: "pay_mana", amount: 7 },
                {
                  type: "return_cards_by_definitions",
                  definitionIds: ["servant.kintoki.skill.sc-kintoki-1", "servant.kintoki.skill.sc-kintoki-2"],
                  fromZone: "removed",
                  destination: "servant-skills",
                  face: "up",
                  count: 2,
                  payloadKey: "goldenShockReturned",
                  then: [{ type: "gain_victory_points", amount: { type: "payload_number", key: "goldenShockReturned", multiply: 2 } }],
                },
              ],
            },
          ],
        }],
      }],
    },
  },
  "servant.hassan.skill.sc-hassan-2": {
    activation: "residual",
    windows: [],
    requiresActiveCard: true,
    handlerId: "core.structured-skill",
    passiveEventTypes: ["card.played", "round.ended"],
    supportLevel: "FULL",
    rules: {
      schemaVersion: "fd-card-authoring-v1",
      abilities: [
        {
          id: "self-modification-play",
          kind: "play_trigger",
          activation: { eventType: "card.played" },
          printedClause: "打出时：隐藏真名并获得2点战果。",
          execution: { mode: "automatic" },
          conditions: [
            { type: "event_player_is_controller" },
            { type: "event_definition_is_self" },
            { type: "event_face_is", face: "up" },
          ],
          effects: [
            { type: "hide_true_name" },
            { type: "gain_victory_points", amount: 2 },
          ],
        },
        {
          id: "self-modification-growth",
          kind: "residual",
          activation: { eventType: "round.ended" },
          requiresActiveCard: true,
          printedClause: "残留：若与你进行交战的玩家本回合被淘汰时，此牌获得威力+1。",
          execution: { mode: "automatic" },
          conditions: [
            { type: "source_active" },
            { type: "event_eliminated_same_battlefield_player" },
          ],
          effects: [{ type: "source_card_power_bonus", amount: 1, duration: "game" }],
        },
      ],
    },
  },
};
